package org.apache.jsp.processmanager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.uengine.security.AclManager;
import java.io.*;
import java.net.*;
import java.util.*;
import javax.naming.InitialContext;
import javax.transaction.*;
import javax.rmi.PortableRemoteObject;
import javax.naming.Context;
import javax.naming.NamingException;
import org.metaworks.*;
import org.metaworks.web.*;
import org.metaworks.inputter.*;
import org.uengine.ui.list.util.HttpUtils;
import org.uengine.ui.list.datamodel.DataMap;
import org.uengine.util.UEngineUtil;
import org.uengine.processmanager.*;
import org.uengine.kernel.*;
import org.uengine.webservices.worklist.*;
import org.uengine.webservice.*;
import org.uengine.security.AclManager;
import org.uengine.contexts.*;
import org.uengine.kernel.GlobalContext;
import com.defaultcompany.login.LoginService;
import org.uengine.kernel.GlobalContext;
import com.defaultcompany.web.acl.*;
import org.uengine.persistence.dao.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


	public String decode(String source) throws Exception{
		//if(source==null)
		//	return null;
		
		return source; //new String(source.getBytes("8859_1"), "UTF-8");
	}
	
	public Object notNull(Object value) throws Exception{
		if(value!=null) return value;
		else return "-";
	}
/*
	public String replaceAmp(String src){
		if(src!=null)
			return src.replaceAll("&", "&amp;");
		else
			return null;
	}
*/

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(10);
    _jspx_dependants.add("/processmanager/../common/topFrame/indexHead.jsp");
    _jspx_dependants.add("/processmanager/../common/topFrame/../header.jsp");
    _jspx_dependants.add("/processmanager/../common/topFrame/../headerMethods.jsp");
    _jspx_dependants.add("/processmanager/../common/topFrame/../getLoggedUser.jsp");
    _jspx_dependants.add("/processmanager/../common/topFrame/../../lib/jquery/importJquery.jsp");
    _jspx_dependants.add("/processmanager/../common/topFrame/indexBodyTop.jsp");
    _jspx_dependants.add("/processmanager/../common/topFrame/topMenuList.jsp");
    _jspx_dependants.add("/processmanager/processDefinitionList.jsp");
    _jspx_dependants.add("/processmanager/../common/topFrame/titleBar.jsp");
    _jspx_dependants.add("/processmanager/../common/footer.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	request.setCharacterEncoding("UTF-8");
    response.setHeader("Cache-Control", "no-cache");

	DataMap reqMap = HttpUtils.getDataMap(request, false);

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

boolean isRegUser = Boolean.parseBoolean(request.getParameter("regUser"));
boolean logged = (session.getAttribute("loggedUserId")!=null)?true:false;   
boolean isCookieLoggin = false;

if(!logged && Boolean.parseBoolean(GlobalContext.getPropertyString("web.cookie.use","false"))){
	LoginService loginService = new LoginService();
	String authenticationCondition = loginService.loginForCookie(request);
	if("Success".equals(authenticationCondition)){
		isCookieLoggin=true;
	}
}

//System.out.println("-----------------------------------------------------");
//System.out.println("getLoggedUser.jsp - logged : "+logged);
//System.out.println("getLoggedUser.jsp - isCookieLoggin : "+isCookieLoggin);
//System.out.println("-----------------------------------------------------");

if (isRegUser) {
	session.setAttribute("loggedUserId", "guest");
} else if (logged == false && isCookieLoggin == false ) {

      out.write("\r\n");
      out.write("<html><meta http-equiv=\"refresh\" content=\"0; url=");
      out.print(org.uengine.kernel.GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/loginForm.jsp\"></meta></html>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\twindow.top.location.href = \"");
      out.print(org.uengine.kernel.GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/loginForm.jsp\";\r\n");
      out.write("</script>\r\n");

	return;
}
	String  loggedUserId       		= (String) session.getAttribute("loggedUserId");
	String  loggedUserFullName 		= (String) session.getAttribute("loggedUserFullName");
	String  loggedUserJikName  		= (String) session.getAttribute("loggedUserJikName");
	String  loggedUserEmail    		= (String) session.getAttribute("loggedUserEmail");
	String  loggedUserPartCode 		= (String) session.getAttribute("loggedUserPartCode");
	String  loggedUserPartName 		= (String) session.getAttribute("loggedUserPartName");
	String  loggedUserMsnId 		= (String) session.getAttribute("loggedUserMsnId");
	String  loggedUserNateonId 		= (String) session.getAttribute("loggedUserNateonId");
	String  loggedUserLocale 		= (String) session.getAttribute("loggedUserLocale");
	String  loggedUserGlobalCom		= (String) session.getAttribute("loggedUserGlobalCom");
	String  loggedUserComName 		= (String) session.getAttribute("loggedUserComName");
	boolean loggedUserIsAdmin  		= "1".equals((String) session.getAttribute("loggedUserIsAdmin"));
	boolean loggedUserIsMaster 		= loggedUserIsAdmin && !org.uengine.util.UEngineUtil.isNotEmpty(loggedUserGlobalCom);
	
	String loggedUserTimeZone		= null;

	org.uengine.kernel.RoleMapping loggedRoleMapping = null;
	String rmClsName = "";
	
	loggedRoleMapping = org.uengine.kernel.RoleMapping.create();
	loggedRoleMapping.setEndpoint(loggedUserId);
	loggedRoleMapping.setResourceName(loggedUserFullName);
	loggedRoleMapping.setEmailAddress(loggedUserEmail);
	loggedRoleMapping.setMale(true);
	loggedRoleMapping.setBirthday(new java.util.Date());
	loggedRoleMapping.setGroupId(loggedUserPartCode);
	loggedRoleMapping.setCompanyId(loggedUserGlobalCom);
	loggedRoleMapping.setLocale(loggedUserLocale);
	loggedRoleMapping.setTitle(loggedUserJikName);
	
	rmClsName = org.uengine.kernel.RoleMapping.USE_CLASS.getName();

      out.write('\r');
      out.write('\n');
      out.write("<link rel='stylesheet' type='text/css' href='");
      out.print(org.uengine.kernel.GlobalContext.WEB_CONTEXT_ROOT );
      out.write("/lib/jquery/jquery-ui.css' />\r\n");
      out.write("<script type='text/javascript' src='");
      out.print(org.uengine.kernel.GlobalContext.WEB_CONTEXT_ROOT );
      out.write("/lib/jquery/jquery-1.12.0.js'></script>\r\n");
      out.write("<script type='text/javascript' src='");
      out.print(org.uengine.kernel.GlobalContext.WEB_CONTEXT_ROOT );
      out.write("/lib/jquery/jquery-ui.js'></script>\r\n");
      out.write("<script type='text/javascript' src='");
      out.print(org.uengine.kernel.GlobalContext.WEB_CONTEXT_ROOT );
      out.write("/lib/jquery/jquery.cookie.js'></script>\r\n");
      out.write("<script>\r\n");
      out.write("jQuery.browser = {};\r\n");
      out.write("(function () {\r\n");
      out.write("    jQuery.browser.msie = false;\r\n");
      out.write("    jQuery.browser.version = 0;\r\n");
      out.write("    if (navigator.userAgent.match(/MSIE ([0-9]+)\\./)) {\r\n");
      out.write("        jQuery.browser.msie = true;\r\n");
      out.write("        jQuery.browser.version = RegExp.$1;\r\n");
      out.write("    }\r\n");
      out.write("})();\r\n");
      out.write("</script>\r\n");
      out.write("<script type='text/javascript' src='");
      out.print(org.uengine.kernel.GlobalContext.WEB_CONTEXT_ROOT );
      out.write("/lib/jquery/jcalendar.js'></script>\r\n");
      out.write("\r\n");
      out.write("<script type='text/javascript' src='");
      out.print(org.uengine.kernel.GlobalContext.WEB_CONTEXT_ROOT );
      out.write("/lib/jquery/ajaxfileupload.js'></script>\r\n");
      out.write("<script type='text/javascript' src='");
      out.print(org.uengine.kernel.GlobalContext.WEB_CONTEXT_ROOT );
      out.write("/lib/jquery/jquery.blink.min.js'></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String sUserLevel = null;
	if (loggedUserIsMaster)
	{
		sUserLevel = "platformmanager";
	}
	else if (loggedUserIsAdmin)
	{
		sUserLevel = "companymanager";
	}
	else
	{
		sUserLevel = "default";
	}


      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Welcome to uEngine BPM</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/dojo/dijit/tests/css/dijitTests.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/dojo/dojox/layout/tests/_expando.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/style/default.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/style/topmenu/topmenu.css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/scripts/common.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/dojo/dojo/dojo.js\" djConfig=\"parseOnLoad:true, isDebug:false\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/dojo/dijit/tests/_testCommon.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/dojo/dojox/layout/ExpandoPane.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/scripts/topmenu.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tdojo.require(\"dojo.data.ItemFileReadStore\");\r\n");
      out.write("\tdojo.require(\"dijit.form.ComboBox\");\r\n");
      out.write("\tdojo.require(\"dijit.Tree\");\r\n");
      out.write("\tdojo.require(\"dijit.layout.AccordionContainer\");\r\n");
      out.write("\tdojo.require(\"dijit.layout.BorderContainer\");\r\n");
      out.write("    dojo.require(\"dijit.Declaration\");\r\n");
      out.write("    dojo.require(\"dojo.data.ItemFileWriteStore\");\r\n");
      out.write("\tdojo.require(\"dijit.Menu\");\r\n");
      out.write("\tdojo.require(\"dojo.parser\");\t// scan page for widgets and instantiate them\r\n");
      out.write("\tdojo.require(\"dijit.layout.LayoutContainer\");   \r\n");
      out.write("    dojo.require(\"dijit.Dialog\");\r\n");
      out.write("    dojo.require(\"dijit.form.Button\");\r\n");
      out.write("    dojo.require(\"dijit.form.TextBox\");\r\n");
      out.write("        \r\n");
      out.write("\tvar global_tn = '';\r\n");
      out.write("\r\n");
      out.write("\tvar req = null;\r\n");
      out.write("\tvar WEB_CONTEXT_ROOT = \"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("\";\r\n");
      out.write("\tvar WEB_ROOT = \"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\tvar getAuthorityList = function() {\r\n");
      out.write("\t\tvar url = WEB_CONTEXT_ROOT + \"/checkWork?userId=");
      out.print(session.getAttribute("loggedUserId"));
      out.write("&todo=newWork\";\r\n");
      out.write("\t\tsubmitAjaxServlet(url, \"Get\", alertNewWork)\r\n");
      out.write("\t}\r\n");
      out.write("\tvar urlNotice = \"http://uengine.org/notice_");
      out.print(loggedUserLocale);
      out.write(".jsp\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction resizeFrame(iframe)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar titleBarHeight = 0;\r\n");
      out.write("\t\tif(isIE)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tiframe.height = \"100%\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ttitleBarHeight = iframe.parentNode.offsetHeight;\r\n");
      out.write("\t\t\tiframe.style.height = (titleBarHeight - 33) + \"px\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write('\r');
      out.write('\n');

	int iMuneNum = 0;
	if (loggedUserIsMaster)
	{
		iMuneNum = 1;
	}
	else
	{
		iMuneNum = 4;
	}

      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"bc\" style=\"width:100%; height:100%;\" dojoType=\"dijit.layout.BorderContainer\">\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');

String logoName = UEngineUtil.isNotEmpty(loggedUserGlobalCom) ? loggedUserGlobalCom : "bpmass";
String notifiedTaskIdStr = (String)session.getAttribute("notifiedTaskId");
String notifiedTaskId = "";
if(notifiedTaskId!=null){
	notifiedTaskId = notifiedTaskIdStr;
}


      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#notification{ position:absolute; right:10px; bottom:0px; background-color:white; border:1px solid #9ca3af; border-bottom:none; width:244px; display:none; z-index:99999;}\r\n");
      out.write("#notification #slide_head{ height:26px; background:url(/uengine-web/images/topmenu/slideup_title.gif) no-repeat; padding:5px; color:#484e58; position:relative; z-index:100000;}\r\n");
      out.write("#notification #slide_head #slide_toggle{position:absolute; top:0px; right:25px; width:22px; height:15px;  background:url(/uengine-web/images/topmenu/slideup_title_bt.gif) no-repeat; cursor:pointer;z-index:100001;}\r\n");
      out.write("#notification #slide_head #slide_close{position:absolute; top:0px; right:5px; width:22px; height:15px;  background:url(/uengine-web/images/topmenu/slideup_title_bt02.gif) no-repeat; cursor:pointer;z-index:100001;}\r\n");
      out.write("#notification #slide_body{ display:block;  padding:5px; color:#484e58;}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction viewTaskInfo(taskid, instanceId, tracingTag) {\r\n");
      out.write("\t\tvar screenWidth = screen.width;\r\n");
      out.write("\t\tvar screenHeight = screen.Height;\r\n");
      out.write("\t\tvar windowWidth = 950;\r\n");
      out.write("\t\tvar windowHeight = 650;\r\n");
      out.write("\t\tvar window_left = (screenWidth - windowWidth) / 2;\r\n");
      out.write("\t\tvar window_top = (screenHeight - windowHeight) / 2;\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar option = \"left=\" + window_left \r\n");
      out.write("\t\t\t\t+ \", top=\" + window_top \r\n");
      out.write("\t\t\t\t+ \", width=\"+ windowWidth \r\n");
      out.write("\t\t\t\t+ \", height=\" + windowHeight\r\n");
      out.write("\t\t\t\t+ \" ,scrollbars=yes,resizable=yes\";\r\n");
      out.write("\t\tvar url = \"/uengine-web/processparticipant/worklist/workitemHandler.jsp?taskId=\" + taskid \r\n");
      out.write("\t\t\t\t+\"&instanceId=\" + instanceId \r\n");
      out.write("\t\t\t\t+\"&tracingTag=\" + tracingTag;\r\n");
      out.write("\t\tvar openedWih = window.open(url, \"processView\", option);\r\n");
      out.write("\t\topenedWih.onclose = refresh;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar USE_NOTIFICATION = true;\r\n");
      out.write("\tvar COOKIE_KEY_NEW_TASKID = \"uEngine.Standalone.newTaskId\";\r\n");
      out.write("\tvar COOKIE_KEY_MSG_VIEW = \"uEngine.Standalone.msgView\";\r\n");
      out.write("\tvar historyTaskId = 0;\r\n");
      out.write("\tvar historyMsgView = true;\r\n");
      out.write("\tvar notificationMessage = null;\r\n");
      out.write("\t\r\n");
      out.write("\tfunction initNotificationMessage(){\r\n");
      out.write("\t\thistoryTaskId = $.cookie(COOKIE_KEY_NEW_TASKID);\r\n");
      out.write("\t\tif(historyTaskId!=null){\r\n");
      out.write("\t\t\thistoryTaskId = parseInt(historyTaskId);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\thistoryMsgView = $.cookie(COOKIE_KEY_MSG_VIEW);\r\n");
      out.write("\t\tif(historyMsgView==null){\r\n");
      out.write("\t\t\thistoryMsgView = true;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\thistoryMsgView = (historyMsgView == \"true\")?true:false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#notification').find(\"div[id='slide_head']\").find(\"div[id='slide_toggle']\").click(function(){\r\n");
      out.write("\t\t\tvar parent = $(this).parent().parent();\r\n");
      out.write("\t\t\tvar bodyheight = parent.height() - $(this).parent().height();\r\n");
      out.write("\t\t\tvar bottom = parent.css(\"bottom\");\r\n");
      out.write("\t\t\tif(parseInt(bottom) < 0){\r\n");
      out.write("\t\t\t\tparent.animate({\"bottom\": \"+=\"+bodyheight+\"px\"}, \"slow\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tparent.animate({\"bottom\": \"-=\"+bodyheight+\"px\"}, \"slow\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#notification').find(\"div[id='slide_head']\").find(\"div[id='slide_close']\").click(function(){\r\n");
      out.write("\t\t\tvar parent = $(this).parent().parent();\r\n");
      out.write("\t\t\tif(!parent.is('hidden')){\r\n");
      out.write("\t\t\t\tparent.hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tsaveHistoryMsgView(false);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar jsonObj = loadNotificationMessage();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(jsonObj){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar newTaskId = parseInt(jsonObj.TASKID);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif((historyTaskId != null && newTaskId == historyTaskId) && historyMsgView == true){\r\n");
      out.write("\t\t\t\tsaveHistoryTaskId(newTaskId);\r\n");
      out.write("\t\t\t\tvar contentData = makeNotificationMessage(jsonObj);\r\n");
      out.write("\t\t\t\tupdateNotificationMessage(contentData);\r\n");
      out.write("\t\t\t\tshowNotificationMessage();\r\n");
      out.write("\t\t\t\t/*\r\n");
      out.write("\t\t\t\tvar notiHead = $('#notification').find(\"div[id='head']\");\r\n");
      out.write("\t\t\t\tvar bodyheight = notiHead.parent().height() - notiHead.height();\r\n");
      out.write("\t\t\t\tnotiHead.parent().css({\"bottom\": \"-\"+bodyheight+\"px\"});\r\n");
      out.write("\t\t\t\t*/\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsetTimeout('reloadNotificationMessage()',3000);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction saveHistoryTaskId(taskId){\r\n");
      out.write("\t\tif($.cookie(COOKIE_KEY_NEW_TASKID)==null){\r\n");
      out.write("\t\t\t$.cookie(COOKIE_KEY_NEW_TASKID, taskId, {'expires':7,'path':\"/\"});\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$.cookie(COOKIE_KEY_NEW_TASKID, null);\r\n");
      out.write("\t\t\t$.cookie(COOKIE_KEY_NEW_TASKID, taskId, {'expires':7,'path':\"/\"});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tsaveHistoryMsgView(true);\r\n");
      out.write("\t\thistoryTaskId = taskId;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction saveHistoryMsgView(bool){\r\n");
      out.write("\t\tif($.cookie(COOKIE_KEY_MSG_VIEW)==null){\r\n");
      out.write("\t\t\t$.cookie(COOKIE_KEY_MSG_VIEW, bool, {'expires':7,'path':\"/\"});\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$.cookie(COOKIE_KEY_MSG_VIEW, null);\r\n");
      out.write("\t\t\t$.cookie(COOKIE_KEY_MSG_VIEW, bool, {'expires':7,'path':\"/\"});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction updateNotificationMessage(htmlData){\r\n");
      out.write("\t\tnotificationMessage = htmlData;\r\n");
      out.write("\t\t$('#notification').find(\"div[id='slide_body']\").html(notificationMessage);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction showNotificationMessage(){\r\n");
      out.write("\t\tif($('#notification').is('hidden')){\r\n");
      out.write("\t\t\t$('#notification').fadeIn(100);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$('#notification').hide();\r\n");
      out.write("\t\t\t$('#notification').fadeIn(100);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction hideNotificationMessage(){\r\n");
      out.write("\t\tif(!$('#notification').is('hidden')){\r\n");
      out.write("\t\t\t$('#notification').fadeOut(100);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction loadNotificationMessage(){\r\n");
      out.write("\t\tvar bodyContent = $.ajax({\r\n");
      out.write("\t\t      url: \"/uengine-web/processparticipant/worklist/wl2_workList_notification.jsp\",\r\n");
      out.write("\t\t      global: false,\r\n");
      out.write("\t\t      type: \"POST\",\r\n");
      out.write("\t\t      dataType: \"json\",\r\n");
      out.write("\t\t      async:false,\r\n");
      out.write("\t\t      success: function(msg){\r\n");
      out.write("\t\t         alert(msg);\r\n");
      out.write("\t\t      }\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t).responseText;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn eval(\"(\"+bodyContent+\")\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction makeNotificationMessage(jsonObj){\r\n");
      out.write("\t\tvar contentData = \"새로운 업무가 도착하였습니다. <br/><strong>\"\r\n");
      out.write("\t\t\t+jsonObj.NAME+\"-\"+jsonObj.TITLE+\"</strong><br/> 시작하려면 \"\r\n");
      out.write("\t\t\t+\"<a href=javascript:viewTaskInfo('\"+jsonObj.TASKID+\"','\"+jsonObj.INSTID+\"','\"+jsonObj.TRCTAG+\"','NEW');>\"\r\n");
      out.write("\t\t\t+\"여기</a>를 클릭하세요.\"\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\treturn contentData;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction reloadNotificationMessage(){\r\n");
      out.write("\t\t//#notification\r\n");
      out.write("\t\tsetTimeout('reloadNotificationMessage()', 60 * 1000);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar jsonObj = loadNotificationMessage();\r\n");
      out.write("\t\tvar contentData = makeNotificationMessage(jsonObj);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(jsonObj.RESULT==\"TRUE\"){\r\n");
      out.write("\t\t\tvar newTaskId = parseInt(jsonObj.TASKID);\r\n");
      out.write("\r\n");
      out.write("\t\t\tif(historyTaskId < newTaskId){\r\n");
      out.write("\t\t\t\tsaveHistoryTaskId(newTaskId);\r\n");
      out.write("\t\t\t\tupdateNotificationMessage(contentData);\r\n");
      out.write("\t\t\t\tshowNotificationMessage();\r\n");
      out.write("\t\t\t} else if(historyTaskId > newTaskId){\r\n");
      out.write("\t\t\t\thideNotificationMessage();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\thideNotificationMessage();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tjQuery(document).ready(function(){\r\n");
      out.write("\t\tinitNotificationMessage();\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"loadframe\">\r\n");
      out.write("\t<div class=\"loadinner\">\r\n");
      out.write("\t\t<div class=\"loadbar\">\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/Common/i_dash_load.gif\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String language = (String)session.getAttribute("loggedUserLocale");
	Authority authority = new Authority();
	
	boolean  isEdition = false;
	if(session.getAttribute("loggedUserIsEdition")!=null){
		isEdition = (Boolean) session.getAttribute("loggedUserIsEdition");
	}

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var topMenuNum = ");
      out.print(iMuneNum);
      out.write(";\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\tif(topMenuNum == 0){\r\n");
      out.write("\t\t$(\"#topMenuList > li.back\").hide();\r\n");
      out.write("\t\t$(\"#topMenuItem_1\").removeClass(\"current\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t$(\"#topMenuList > li\").mouseover(function(){\r\n");
      out.write("\t\tvar targetObj = $(this);\r\n");
      out.write("\t\ttargetObj.addClass(\"current\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(topMenuNum == 0){\r\n");
      out.write("\t\t\t$(\"#topMenuList > li.back\").show();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif(\"topMenuItem_\"+topMenuNum != targetObj.attr(\"id\")){\r\n");
      out.write("\t\t\t\t$(\"#topMenuItem_\"+topMenuNum).removeClass(\"current\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}).mouseout(function(){\r\n");
      out.write("\t\tvar targetObj = $(this);\r\n");
      out.write("\t\ttargetObj.removeClass(\"current\");\r\n");
      out.write("\t\tif(topMenuNum == 0){\r\n");
      out.write("\t\t\t$(\"#topMenuList > li.back\").hide();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif(\"topMenuItem_\"+topMenuNum != targetObj.attr(\"id\")){\r\n");
      out.write("\t\t\t\t$(\"#topMenuItem_\"+topMenuNum).addClass(\"current\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"flashArea\">\r\n");
      out.write("\t<div style=\"width:100%; height:1px; line-height:1px;\"></div>\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t    <ul class=\"menu\" id=\"topMenuList\">\r\n");
      out.write("\t    ");

			if(sUserLevel.equals("default")){
		
      out.write("\r\n");
      out.write("\t        <li id=\"topMenuItem_1\" class=\"");
      out.print((iMuneNum==1)? "current": "");
      out.write("\"><a href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/processparticipant/worklist/index.jsp\" class=\"parent\"><span>");
      out.print(GlobalContext.getMessageForWeb("title.worklist", loggedUserLocale));
      out.write("</span></a></li>\r\n");
      out.write("\t        <li style=\"width:2px; height:40px; background:url(");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/topmenu/menuLine.gif) no-repeat 0 15px;\"></li>\r\n");
      out.write("\t        <li id=\"topMenuItem_2\" class=\"");
      out.print((iMuneNum==2)? "current": "");
      out.write("\"><a href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/processparticipant/participationProcess/index.jsp\" class=\"parent\"><span>");
      out.print(GlobalContext.getMessageForWeb("title.participation", loggedUserLocale));
      out.write("</span></a></li>\r\n");
      out.write("\t        <li style=\"width:2px; height:40px; background:url(");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/topmenu/menuLine.gif) no-repeat 0 15px;\"></li>\r\n");
      out.write("\t        <li id=\"topMenuItem_3\" class=\"");
      out.print((iMuneNum==3)? "current": "");
      out.write("\"><a href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/processparticipant/index.jsp\" class=\"parent\"><span>");
      out.print(GlobalContext.getMessageForWeb("title.process", loggedUserLocale));
      out.write("</span></a></li>\r\n");
      out.write("\t        ");
      out.write("\r\n");
      out.write("\t        ");
 if(isEdition){
      out.write("\r\n");
      out.write("\t\t        <li id=\"topMenuItem_4\" class=\"");
      out.print((iMuneNum==4)? "current": "");
      out.write("\"><a href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/processmanager/index.jsp\" class=\"parent\"><span>");
      out.print(GlobalContext.getMessageForWeb("title.processmanager", loggedUserLocale));
      out.write("</span></a></li>\r\n");
      out.write("\t        ");
 }
			}if(sUserLevel.equals("platformmanager")){
			
      out.write("\r\n");
      out.write("\t        <li id=\"topMenuItem_1\" class=\"");
      out.print((iMuneNum==1)? "current": "");
      out.write("\"><a href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/processmanager/index.jsp\" class=\"parent\"><span>");
      out.print(GlobalContext.getMessageForWeb("title.processmanager", loggedUserLocale));
      out.write("</span></a></li>\r\n");
      out.write("\t        <li style=\"width:2px; height:40px; background:url(");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/topmenu/menuLine.gif) no-repeat 0 15px;\"></li>\r\n");
      out.write("\t        <li id=\"topMenuItem_2\" class=\"");
      out.print( (iMuneNum==2)? "current": "");
      out.write("\"><a href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/organizationmanager/index.jsp\" class=\"parent\"><span>");
      out.print(GlobalContext.getMessageForWeb("title.organization", loggedUserLocale));
      out.write("</span></a></li>\r\n");
      out.write("\t\t");

			}if(sUserLevel.equals("companymanager")){
		
      out.write("\r\n");
      out.write("\t        <li id=\"topMenuItem_1\" class=\"");
      out.print((iMuneNum==1)? "current": "");
      out.write("\"><a href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/processparticipant/worklist/index.jsp\" class=\"parent\"><span>");
      out.print(GlobalContext.getMessageForWeb("title.worklist", loggedUserLocale));
      out.write("</span></a></li>\r\n");
      out.write("\t        <li style=\"width:2px; height:40px; background:url(");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/topmenu/menuLine.gif) no-repeat 0 15px;\"></li>\r\n");
      out.write("\t        <li id=\"topMenuItem_2\" class=\"");
      out.print((iMuneNum==2)? "current": "");
      out.write("\"><a href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/processparticipant/participationProcess/index.jsp\" class=\"parent\"><span>");
      out.print(GlobalContext.getMessageForWeb("title.participation", loggedUserLocale));
      out.write("</span></a></li>\r\n");
      out.write("\t        <li style=\"width:2px; height:40px; background:url(");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/topmenu/menuLine.gif) no-repeat 0 15px;\"></li>\r\n");
      out.write("\t        <li id=\"topMenuItem_3\" class=\"");
      out.print((iMuneNum==3)? "current": "");
      out.write("\"><a href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/processparticipant/index.jsp\" class=\"parent\"><span>");
      out.print(GlobalContext.getMessageForWeb("title.process", loggedUserLocale));
      out.write("</span></a></li>\r\n");
      out.write("\t        <li style=\"width:2px; height:40px; background:url(");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/topmenu/menuLine.gif) no-repeat 0 15px;\"></li>\r\n");
      out.write("\t        <li id=\"topMenuItem_7\" class=\"");
      out.print((iMuneNum==7)? "current": "");
      out.write("\"><a href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/monitor/index.jsp\" class=\"parent\"><span>");
      out.print(GlobalContext.getMessageForWeb("title.monitor", loggedUserLocale));
      out.write("</span></a></li>\r\n");
      out.write("\t        <li style=\"width:2px; height:40px; background:url(");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/topmenu/menuLine.gif) no-repeat 0 15px;\"></li>\r\n");
      out.write("\t        <li id=\"topMenuItem_4\" class=\"");
      out.print((iMuneNum==4)? "current": "");
      out.write("\"><a href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/processmanager/index.jsp\" class=\"parent\"><span>");
      out.print(GlobalContext.getMessageForWeb("title.processmanager", loggedUserLocale));
      out.write("</span></a></li>\r\n");
      out.write("\t        <li style=\"width:2px; height:40px; background:url(");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/topmenu/menuLine.gif) no-repeat 0 15px;\"></li>\r\n");
      out.write("\t        <li id=\"topMenuItem_5\" class=\"");
      out.print((iMuneNum==5)? "current": "");
      out.write("\"><a href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/organizationmanager/index.jsp\" class=\"parent\"><span>");
      out.print(GlobalContext.getMessageForWeb("title.organization", loggedUserLocale));
      out.write("</span></a></li>\r\n");
      out.write("\t        ");
      out.write("\r\n");
      out.write("\t    ");
	} 
      out.write("\r\n");
      out.write("\t    </ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"copyright\" style=\"display:none;\">Copyright &copy; 2010 <a href=\"http://apycom.com/\">Apycom jQuery Menus</a></div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"header\" dojoType=\"dijit.layout.ContentPane\" region=\"top\" style=\"height:74px; border:none; background:url(");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/Common/topbg_default.gif);\">\r\n");
      out.write("\t<div id=\"logo\">\r\n");
      out.write("\t<!--<a href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/index.jsp\"><img src=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/portrait/groups/");
      out.print(logoName );
      out.write("_logo.gif\" width=\"197\" height=\"74\"></a>-->\t\r\n");
      out.write("\t<a href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/index.jsp\"><img src=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/portrait/groups/gpmEngine_logo.png\" width=\"197\" height=\"74\"></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<form id=\"titleform\" name=\"titleform\" action=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/logout.jsp\" target=\"_top\" method=\"post\">\r\n");
      out.write("\t\t<div id=\"topline\">\r\n");
      out.write("\t        <div class=\"userbtn\"><a href=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/organizationmanager/userInfoByself.jsp\" target=\"innerworkarea\" class=\"rollover\"><img src=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/Common/B_EditInfo_");
      out.print(loggedUserLocale);
      out.write(".gif\" /><img src=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/Common/B_EditInfo_on_");
      out.print(loggedUserLocale);
      out.write(".gif\" class=\"over\" /></a>&nbsp;<a href=\"javascript:titleform.submit();\" class=\"rollover\"><img src=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/Common/B_LogoOut_");
      out.print(loggedUserLocale);
      out.write(".gif\" /><img src=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/Common/B_LogoOut_on_");
      out.print(loggedUserLocale);
      out.write(".gif\" class=\"over\"/></a>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"userinfo\">\r\n");
      out.write("\t        \t<span class=\"fontbold\">");
      out.print(loggedUserComName);
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(loggedUserFullName);
      out.write("</span>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Notification Message Div -->\r\n");
      out.write("<div id=\"notification\">\r\n");
      out.write("\t<div id=\"slide_head\"><div id=\"slide_toggle\"></div><div id=\"slide_close\"></div><div>알립니다.</div></div>\r\n");
      out.write("\t<div id=\"slide_body\"></div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t<div dojoType=\"dojox.layout.ExpandoPane\" \r\n");
      out.write("\t\t\t\t\tsplitter=\"true\" \r\n");
      out.write("\t\t\t\t\tduration=\"125\" \r\n");
      out.write("\t\t\t\t\tregion=\"left\" \r\n");
      out.write("\t\t\t\t\ttitle=\"");
      out.print(GlobalContext.getMessageForWeb("Process", loggedUserLocale));
      out.write("\" \r\n");
      out.write("\t\t\t\t\tid=\"leftPane\" \r\n");
      out.write("\t\t\t\t\tmaxWidth=\"275\" \r\n");
      out.write("\t\t\t\t\tstyle=\"width: 250px; background: #fafafa;\">\r\n");
      out.write("\t\t");
      out.write('\r');
      out.write('\n');

    String target = request.getParameter("target");

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../scripts/formActivity.js.jsp" + (("../scripts/formActivity.js.jsp").indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("rmClsName", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(rmClsName), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("    setCalender(\"");
      out.print(loggedUserLocale);
      out.write("\", {buttonImage:\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/Icon/btn_calendar.gif\"});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function viewObjectType(objType ,id, folder){\r\n");
      out.write("    if(objType==\"process\"){\r\n");
      out.write("        document.viewProcessDefinition.processDefinition.value=id;\r\n");
      out.write("        document.viewProcessDefinition.folder.value=folder;     \r\n");
      out.write("        document.viewProcessDefinition.submit();\r\n");
      out.write("    }else if(objType==\"rule\"){\r\n");
      out.write("        document.viewRuleDefinition.objectDefinitionId.value=id;\r\n");
      out.write("        document.viewRuleDefinition.folder.value=folder;        \r\n");
      out.write("        document.viewRuleDefinition.submit();\r\n");
      out.write("    }else if(objType==\"class\"){\r\n");
      out.write("        document.viewClassDefinition.objectDefinitionId.value=id;\r\n");
      out.write("        document.viewClassDefinition.folder.value=folder;       \r\n");
      out.write("        document.viewClassDefinition.submit();\r\n");
      out.write("    }else if(objType==\"form\"){\r\n");
      out.write("        document.viewFormDefinition.objectDefinitionId.value=id;\r\n");
      out.write("        document.viewFormDefinition.folder.value=folder;        \r\n");
      out.write("        document.viewFormDefinition.submit();\r\n");
      out.write("        \r\n");
      out.write("        //document.viewFormDefinitionUSFeditor.objectDefinitionId.value=id;\r\n");
      out.write("        //document.viewFormDefinitionUSFeditor.folder.value=folder;        \r\n");
      out.write("        //document.viewFormDefinitionUSFeditor.submit();\r\n");
      out.write("    }else if(objType==\"excel\"){\r\n");
      out.write("        document.viewCalcDefinition.objectDefinitionId.value=id;\r\n");
      out.write("        document.viewCalcDefinition.folder.value=folder;        \r\n");
      out.write("        document.viewCalcDefinition.submit();\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("function newObject(objType,defId){\r\n");
      out.write("    if(defId==undefined || defId==\"continentRoot\") defId=-1;\r\n");
      out.write("\r\n");
      out.write("    if(objType==\"process\"){\r\n");
      out.write("        location='ProcessDesigner.jnlp?folderId='+defId;\r\n");
      out.write("    }else if(objType==\"rule\"){\r\n");
      out.write("        document.newRuleDefinition.folderId.value=defId;    \r\n");
      out.write("        document.newRuleDefinition.submit();\r\n");
      out.write("    }else if(objType==\"class\"){\r\n");
      out.write("        document.newClassDefinition.folderId.value=defId;       \r\n");
      out.write("        document.newClassDefinition.submit();\r\n");
      out.write("    }else if(objType==\"formCK\"){\r\n");
      out.write("        document.newFormDefinition.folderId.value=defId;        \r\n");
      out.write("        document.newFormDefinition.submit();\r\n");
      out.write("    }else if(objType==\"formUSF\"){\r\n");
      out.write("        document.newFormDefinitionUSFeditor.folderId.value=defId;        \r\n");
      out.write("        document.newFormDefinitionUSFeditor.submit();\r\n");
      out.write("    }else if(objType==\"crud_app\"){\r\n");
      out.write("        document.newDatabaseSet.folderId.value=defId;       \r\n");
      out.write("        document.newDatabaseSet.submit();\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function addFolder(parent){\r\n");
      out.write("    if(parent==undefined || parent==\"continentRoot\") parent=-1;\r\n");
      out.write("    document.addFolderForm.parentFolder.value=parent;\r\n");
      out.write("    dijit.byId('addFolderDialog').show();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var definitionId = null;\r\n");
      out.write("function moveFolder(tempDefinitionId, definitionName){\r\n");
      out.write("    var url = \"../processparticipant/commonfilter/selectProcessDefinition_frame.jsp?moveToDef=Y\";\r\n");
      out.write("    var StrOption = \"width=500,height=300,scroll=auto,resizable=false\";\r\n");
      out.write("\r\n");
      out.write("    definitionId = tempDefinitionId;\r\n");
      out.write("    window.open (url , \"\", StrOption);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function actionMoveFolder(parentFolder) {\r\n");
      out.write("    document.location.href = WEB_CONTEXT_ROOT + \"/processmanager/moveProcessDefinition.jsp?processDefinition=\" + definitionId\r\n");
      out.write("            + \"&parentFolder=\" + parentFolder;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function rename(processDefinition, definitionName){\r\n");
      out.write("    document.actionForm.processDefinition.value=processDefinition;\r\n");
      out.write("    dijit.byId('reNameDialog').show();\r\n");
      out.write("\r\n");
      out.write("    var tempTest = document.getElementsByName(\"newname\");\r\n");
      out.write("    for (var i = 0, il = tempTest.length; i < il; i++)\r\n");
      out.write("    {\r\n");
      out.write("        tempTest[i].value = definitionName;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function remove(processDefinition) {\r\n");
      out.write("    if (confirm(\"Are you sure to delete this processdefinition?\")) {\r\n");
      out.write("        document.removeForm.folder.value=processDefinition;\r\n");
      out.write("        document.removeForm.submit();\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("        \r\n");
      out.write("function exportDef(processDefinition){\r\n");
      out.write("    if(processDefinition==undefined || processDefinition==\"continentRoot\") processDefinition=-1;\r\n");
      out.write("    document.exportDef.processDefinition.value=processDefinition;\r\n");
      out.write("    document.exportDef.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function importDefDialog(processDefinition){\r\n");
      out.write("    if(processDefinition==undefined || processDefinition==\"continentRoot\") processDefinition=-1;\r\n");
      out.write("    document.importDef.definitionId.value=processDefinition;\r\n");
      out.write("    \r\n");
      out.write("    var dialogOpts = {\r\n");
      out.write("            autoOpen: false,\r\n");
      out.write("            width: 300,\r\n");
      out.write("            modal : true,\r\n");
      out.write("            resizable: true,\r\n");
      out.write("            buttons: [{\r\n");
      out.write("                text: \"");
      out.print(GlobalContext.getMessageForWeb("OK", loggedUserLocale) );
      out.write("\",\r\n");
      out.write("                click: function() { fnImportDef() }\r\n");
      out.write("            }]\r\n");
      out.write("    };\r\n");
      out.write("    \r\n");
      out.write("    jQuery(\"#importDefDialog\").dialog(dialogOpts);\r\n");
      out.write("    jQuery(\"#importDefDialog\").dialog(\"open\");\r\n");
      out.write("    $(\"#importDefDialog\").css(\"height\", 40);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fnImportDef() {\r\n");
      out.write("    $(\"#divImport\").append($(\"#importDefPath\"));\r\n");
      out.write("    document.importDef.submit();\r\n");
      out.write("    $(\"#divInputFile\").append($(\"#importDefPath\"));\r\n");
      out.write("    jQuery(\"#importDefDialog\").dialog(\"close\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* \r\n");
      out.write(" * Authority management\r\n");
      out.write(" */\r\n");
      out.write("function accessibility(item){\r\n");
      out.write("    document.accessibility.defId.value = item.id;\r\n");
      out.write("    document.accessibility.defName.value = item.name;\r\n");
      out.write("    document.accessibility.submit();\r\n");
      out.write("    //alert(\"You can't use this function, In standalone version\");\r\n");
      out.write("}\r\n");
      out.write("      \r\n");
      out.write("function toggleVisible(defId, isVisible){\r\n");
      out.write("    if(defId==undefined || defId==\"continentRoot\") defId=-1;\r\n");
      out.write("\r\n");
      out.write("    document.toggleVisibleForm.definitionId.value=defId;\r\n");
      out.write("    document.toggleVisibleForm.visible.value=isVisible;\r\n");
      out.write("    document.toggleVisibleForm.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Serach instance\r\n");
      out.write("function search() {\r\n");
      out.write("    //document.searchForm.target = \"right\";\r\n");
      out.write("    document.searchForm.submit();       \r\n");
      out.write("}\r\n");
      out.write("function callback(cal) {\r\n");
      out.write("    //checkDate();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var userType = 'initiator';\r\n");
      out.write("\r\n");
      out.write("function selectUser(id, name, loginName) {\r\n");
      out.write("    if ( userType == 'initiator' ) {\r\n");
      out.write("        document.searchForm.initiatorId.value = id;\r\n");
      out.write("        document.searchForm.initiatorName.value = name;\r\n");
      out.write("        document.searchForm.initiatorLoginName.value = loginName;\r\n");
      out.write("    } else if ( userType == 'currentUser' ) {\r\n");
      out.write("        document.searchForm.currentUserId.value = id;\r\n");
      out.write("        document.searchForm.currentUserName.value = name;\r\n");
      out.write("        document.searchForm.currentUserLoginName.value = loginName;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function initInputBox() {\r\n");
      out.write("    var sForm = document.searchForm;\r\n");
      out.write("    sForm.initiatorId.value = \"\";\r\n");
      out.write("    sForm.initiatorName.value = \"\";\r\n");
      out.write("    sForm.currentUserId.value = \"\";\r\n");
      out.write("    sForm.currentUserName.value = \"\";\r\n");
      out.write("    sForm.init_start_date.value = \"\";\r\n");
      out.write("    sForm.init_end_date.value = \"\";\r\n");
      out.write("    sForm.due_start_date.value = \"\";\r\n");
      out.write("    sForm.due_end_date.value = \"\";\r\n");
      out.write("    sForm.complete_start_date.value = \"\";\r\n");
      out.write("    sForm.complete_end_date.value = \"\";\r\n");
      out.write("    sForm.docTitle.value = \"\";\r\n");
      out.write("    sForm.workName.value = \"\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function reNameDialog(name){\r\n");
      out.write("    if(name !=null && name !=\"\" && name!=\"null\"){\r\n");
      out.write("        document.actionForm.newName.value = name;\r\n");
      out.write("        document.actionForm.submit();\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function addFolderDialog(name){\r\n");
      out.write("    if(name !=null && name !=\"\" && name!=\"null\"){\r\n");
      out.write("        document.addFolderForm.folderName.value=name;\r\n");
      out.write("        document.addFolderForm.submit();\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getChildNodesForAjax(item) {\r\n");
      out.write("\tvar firstChild = item.children[0];\r\n");
      out.write("\tif(firstChild.type == \"temp\") {\r\n");
      out.write("\t\tcontinentStore.deleteItem(firstChild);\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"makeProcessDefinitionListJson.jsp\",\r\n");
      out.write("\t\t\tdata : \"parentDefId=\" + item.id,\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess :function (data, textStatus, jqXHR) {\r\n");
      out.write("\t\t\t\t$(data.items).each(function(index, defItem) {\r\n");
      out.write("\t\t\t\t\tvar newItem = continentStore.newItem(defItem, {parent : item, attribute : \"children\"});\r\n");
      out.write("\t\t\t\t\tif (defItem.obj == \"folder\" && parseInt(defItem.childCnt) > 0) {\r\n");
      out.write("\t\t\t\t\t\tvar tempChild = {id : \"temp_\" + index + defItem.obj + \"_\" + defItem.id, name : \"tempChildrenForItem\", type : \"temp\"};\r\n");
      out.write("\t\t\t\t\t\tcontinentStore.newItem(tempChild, {parent : newItem, attribute : \"children\"});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function addChildNodeData(definitionStore, data) {\r\n");
      out.write("\tvar tempChild = {id : \"temp_\" + 0 + data.obj + \"_\" + data.id, name : \"tempChildrenForItem\", type : \"folder\"};\r\n");
      out.write("\tdefinitionStore.newItem(tempChild, {parent : data, attribute : \"children\"});\r\n");
      out.write("}\r\n");
      out.write("        \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"soria\">\r\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"reNameDialog\" title=\"insert newname\" execute=\"reNameDialog(arguments[0].newname);\">\r\n");
      out.write("    <table>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td><label for=\"newname\">");
      out.print(GlobalContext.getMessageForWeb("Name", loggedUserLocale) );
      out.write(" : </label></td>\r\n");
      out.write("            <td><input dojoType=\"dijit.form.TextBox\" type=\"text\" name=\"newname\" id=\"newname\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td colspan=\"2\" align=\"center\"><button dojoType=\"dijit.form.Button\" type=\"submit\">OK</button></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("</div>\r\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"addFolderDialog\" title=\"insert name\" execute=\"addFolderDialog(arguments[0].name);\">\r\n");
      out.write("    <table>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td><label for=\"name\">");
      out.print(GlobalContext.getMessageForWeb("Name", loggedUserLocale) );
      out.write(" : </label></td>\r\n");
      out.write("            <td><input dojoType=\"dijit.form.TextBox\" type=\"text\" name=\"name\" id=\"name\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td colspan=\"2\" align=\"center\"><button dojoType=\"dijit.form.Button\" type=\"submit\">");
      out.print(GlobalContext.getMessageForWeb("OK", loggedUserLocale) );
      out.write("</button></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<form name=\"importDef\" action=\"importDefinition.jsp\" enctype=\"multipart/form-data\" method=\"post\" target=\"innerworkarea\">\r\n");
      out.write("    <input type=\"hidden\" name=\"definitionId\">\r\n");
      out.write("    <div id=\"divImport\"></div>\r\n");
      out.write("    <div id=\"importDefDialog\" title=\"Select Definition\" style=\"display: none; height:100%;\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div id=\"divInputFile\"><input type=\"file\" name=\"importDefPath\" id=\"importDefPath\" /></div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<div dojoType=\"dojo.data.ItemFileWriteStore\" jsId=\"continentStore\" url=\"json/jsonConfig.json\"></div>\r\n");
      out.write("<div dojoType=\"dijit.tree.ForestStoreModel\" jsId=\"continentModel\" store=\"continentStore\" rootId=\"continentRoot\" rootLabel=\"Definitions\" childrenAttrs=\"children\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- ########## changed menu code here ########## -->\r\n");
      out.write("<ul dojoType=\"dijit.Menu\" id=\"folder_menu\" style=\"display: none;\">\r\n");
      out.write("    <li dojoType=\"dijit.MenuItem\" onclick=\"viewObjectType(global_tn.item.obj,global_tn.item.id,global_tn.item.parent);\">");
      out.print(GlobalContext.getMessageForWeb("View", loggedUserLocale) );
      out.write("</li>\r\n");

if (!(GlobalContext.getPropertyString("aclmanager.class", "").equals("") || GlobalContext.getPropertyString("aclmanager.class", "").indexOf("DefaultNonAclUtil") > -1)) {

      out.write("\r\n");
      out.write("    <li dojoType=\"dijit.MenuItem\" onclick=\"accessibility(global_tn.item)\">");
      out.print(GlobalContext.getMessageForWeb("Set Authority", loggedUserLocale) );
      out.write("</li>\r\n");

}

      out.write("\r\n");
      out.write("    <li dojoType=\"dijit.MenuItem\" onclick=\"rename(global_tn.item.id, global_tn.item.name)\">");
      out.print(GlobalContext.getMessageForWeb("Rename", loggedUserLocale) );
      out.write("</li>\r\n");
      out.write("    <li dojoType=\"dijit.MenuItem\" onclick=\"remove(global_tn.item.id)\">");
      out.print(GlobalContext.getMessageForWeb("Remove", loggedUserLocale) );
      out.write("</li>\r\n");
      out.write("    <li dojoType=\"dijit.MenuItem\" onclick=\"moveFolder(global_tn.item.id,global_tn.item.name)\">");
      out.print(GlobalContext.getMessageForWeb("Move", loggedUserLocale) );
      out.write("</li>\r\n");
      out.write("    <li dojoType=\"dijit.MenuItem\" onclick=\"document.location.reload()\">");
      out.print(GlobalContext.getMessageForWeb("Refresh", loggedUserLocale) );
      out.write("</li>\r\n");
      out.write("    <!--li dojoType=\"dijit.PopupMenuItem\">\r\n");
      out.write("            <span>Visible</span>\r\n");
      out.write("            <ul dojoType=\"dijit.Menu\" id=\"submenu1\" >\r\n");
      out.write("                <li dojoType=\"dijit.MenuItem\" onClick=\"toggleVisible(global_tn.item.id,\"true\")\">visible</li>\r\n");
      out.write("                <li dojoType=\"dijit.MenuItem\" onClick=\"toggleVisible(global_tn.item.id,\"false\")\">invisible</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li-->\r\n");
      out.write("    <li dojoType=\"dijit.PopupMenuItem\">\r\n");
      out.write("        <span>");
      out.print(GlobalContext.getMessageForWeb("New", loggedUserLocale) );
      out.write("</span>\r\n");
      out.write("        <ul dojoType=\"dijit.Menu\" id=\"submenu2\">\r\n");
      out.write("            <li dojoType=\"dijit.MenuItem\" onclick=\"newObject('process',global_tn.item.id)\" >");
      out.print(GlobalContext.getMessageForWeb("Process", loggedUserLocale) );
      out.write("</li>\r\n");
      out.write("            <!-- li dojoType=\"dijit.MenuItem\" onClick=\"newObject('rule',global_tn.item.id)\" >");
      out.print(GlobalContext.getMessageForWeb("Rule", loggedUserLocale) );
      out.write("</li-->\r\n");
      out.write("            <li dojoType=\"dijit.MenuItem\" onclick=\"newObject('formCK',global_tn.item.id)\" >");
      out.print(GlobalContext.getMessageForWeb("Form", loggedUserLocale) );
      out.write("</li>\r\n");
      out.write("<!--\r\n");
      out.write("            <li dojoType=\"dijit.PopupMenuItem\">\r\n");
      out.write("                <span>");
      out.print(GlobalContext.getMessageForWeb("Form", loggedUserLocale) );
      out.write("</span>\r\n");
      out.write("                <ul dojoType=\"dijit.Menu\" id=\"subsubmenu1\">\r\n");
      out.write("                    <li dojoType=\"dijit.MenuItem\" onclick=\"newObject('formCK',global_tn.item.id)\" >ckEditor</li>\r\n");
      out.write("                    <li dojoType=\"dijit.MenuItem\" onclick=\"newObject('formUSF',global_tn.item.id)\" >usfEditor</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("-->\r\n");
      out.write("            <!-- li dojoType=\"dijit.MenuItem\" onClick=\"newObject('class',global_tn.item.id)\" >");
      out.print(GlobalContext.getMessageForWeb("Class", loggedUserLocale) );
      out.write("</li-->\r\n");
      out.write("            <li dojoType=\"dijit.MenuItem\" onclick=\"addFolder(global_tn.item.id)\" >");
      out.print(GlobalContext.getMessageForWeb("Child Folder", loggedUserLocale) );
      out.write("</li>\r\n");
      out.write("            <!-- li dojoType=\"dijit.MenuItem\" onClick=\"newObject('excel',global_tn.item.id)\" >");
      out.print(GlobalContext.getMessageForWeb("JCalc", loggedUserLocale) );
      out.write("</li-->\r\n");
      out.write("            <!--li dojoType=\"dijit.MenuItem\" onClick=\"newObject('crud_app',global_tn.item.id)\" >");
      out.print(GlobalContext.getMessageForWeb("Crud App", loggedUserLocale) );
      out.write("</li-->\r\n");
      out.write("        </ul>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li dojoType=\"dijit.PopupMenuItem\">\r\n");
      out.write("        <span>");
      out.print(GlobalContext.getMessageForWeb("Im/Export", loggedUserLocale) );
      out.write("</span>\r\n");
      out.write("        <ul dojoType=\"dijit.Menu\" id=\"submenu3\" >\r\n");
      out.write("            <li dojoType=\"dijit.MenuItem\" onclick=\"importDefDialog(global_tn.item.id)\">");
      out.print(GlobalContext.getMessageForWeb("Import", loggedUserLocale) );
      out.write("</li>\r\n");
      out.write("            <li dojoType=\"dijit.MenuItem\" onclick=\"exportDef(global_tn.item.id)\">");
      out.print(GlobalContext.getMessageForWeb("Export", loggedUserLocale) );
      out.write("</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </li>\r\n");
      out.write("</ul>\r\n");
      out.write("<!-- ############################################ -->\r\n");
      out.write("\r\n");
      out.write("<div dojoType=\"dijit.layout.LayoutContainer\" style=\"width: 100%; height: 100%; padding: 0; margin: 0; border: 0;\">\r\n");
      out.write("    <div dojoType=\"dijit.layout.AccordionContainer\" layoutAlign=\"client\">\r\n");
      out.write("        <!-- First accordion : Process -->\r\n");
      out.write("        <div dojoType=\"dijit.layout.AccordionPane\" title=\"");
      out.print(GlobalContext.getMessageForWeb("Definition List", loggedUserLocale) );
      out.write("\">\r\n");
      out.write("            <div dojoType=\"dijit.Tree\" id=\"definitionTree\" model=\"continentModel\" childrenAttr=\"children\"  showRoot=\"false\" openOnClick=\"false\" >\r\n");
      out.write("                <script type=\"dojo/connect\">\r\n");
      out.write("                        var menuEmpty = dijit.byId(\"folder_menu\");\r\n");
      out.write("                \r\n");
      out.write("                        menuEmpty.bindDomNode(this.domNode);\r\n");
      out.write("                \r\n");
      out.write("                        dojo.connect(menuEmpty, \"_openMyself\", this, function(e) {\r\n");
      out.write("                            global_tn = dijit.getEnclosingWidget(e.target);\r\n");
      out.write("\r\n");
      out.write("                            if (global_tn.item.id == \"continentRoot\") {\r\n");
      out.write("                                menuEmpty.getChildren().forEach(function(i) { \r\n");
      out.write("                                    if ( \r\n");
      out.write("                                        i.id==\"dijit_MenuItem_0\" ||\r\n");
      out.write("                                        i.id==\"dijit_MenuItem_1\" ||\r\n");
      out.write("                                        i.id==\"dijit_MenuItem_2\" ||\r\n");
      out.write("                                        i.id==\"dijit_MenuItem_3\" ||\r\n");
      out.write("                                        i.id==\"dijit_MenuItem_4\"  \r\n");
      out.write("                                    ) {\r\n");
      out.write("                                        i.setDisabled(true); \r\n");
      out.write("                                    } else {\r\n");
      out.write("                                        i.setDisabled(false); \r\n");
      out.write("                                    }\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if (global_tn.item.obj == \"folder\") {\r\n");
      out.write("                                menuEmpty.getChildren().forEach(function(i) {\r\n");
      out.write("                                    if (i.id == \"dijit_MenuItem_0\") {\r\n");
      out.write("                                        i.setDisabled(true); \r\n");
      out.write("                                    } else {\r\n");
      out.write("                                        i.setDisabled(false); \r\n");
      out.write("                                    }\r\n");
      out.write("                                });                 \r\n");
      out.write("                            } else {\r\n");
      out.write("                                menuEmpty.getChildren().forEach(function(i) {\r\n");
      out.write("                                    if (i.id == \"dijit_PopupMenuItem_0\" || i.id == \"dijit_PopupMenuItem_1\") {\r\n");
      out.write("                                        i.setDisabled(true); \r\n");
      out.write("                                    } else {\r\n");
      out.write("                                        i.setDisabled(false); \r\n");
      out.write("                                    }\r\n");
      out.write("                                });\r\n");
      out.write("                            }\r\n");
      out.write("                        });\r\n");
      out.write("                    </script>\r\n");
      out.write("                    <script type=\"dojo/method\" event=\"getIconClass\" args=\"item, opened\">\r\n");
      out.write("                        if (item.type == \"root\") {\r\n");
      out.write("                            ObjType = \"definition\";\r\n");
      out.write("                        } else if(item.obj == \"folder\") {\r\n");
      out.write("                            ObjType = \"folder\";\r\n");
      out.write("                        } else {\r\n");
      out.write("                            ObjType = item.obj;\r\n");
      out.write("                        }\r\n");
      out.write("           \r\n");
      out.write("                        if (ObjType == \"folder\") {\r\n");
      out.write("                            ObjType = opened ? \"folderOpenIcon\" : \"folderClosedIcon\";\r\n");
      out.write("                        } else {\r\n");
      out.write("                            ObjType += \"Icon\";\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        return ObjType;\r\n");
      out.write("                    </script>\r\n");
      out.write("                    <script type=\"dojo/method\" event=\"onClick\" args=\"item\">\r\n");
      out.write("                        if (item.obj != \"folder\") {\r\n");
      out.write("                            viewObjectType(item.obj, item.id, item.parent);\r\n");
      out.write("                        }\r\n");
      out.write("                    </script>\r\n");
      out.write("                    <script type=\"dojo/method\" event=\"onOpen\" args=\"item, node\">\r\n");
      out.write("                        getChildNodesForAjax(item);\r\n");
      out.write("                    </script>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Second accordion : Instances -->\r\n");
      out.write("        <div dojoType=\"dijit.layout.AccordionPane\" title=\"");
      out.print(GlobalContext.getMessageForWeb("Search Instance", loggedUserLocale) );
      out.write("\">\r\n");
      out.write("            <form name=\"searchForm\" method=\"post\" action=\"processInstanceListDetail.jsp\" target=\"innerworkarea\">\r\n");
      out.write("                <input type=\"hidden\" name=\"initiatorId\" />\r\n");
      out.write("                <input type=\"hidden\" name=\"initiatorLoginName\" />\r\n");
      out.write("                <input type=\"hidden\" name=\"currentUserId\" />\r\n");
      out.write("                <input type=\"hidden\" name=\"currentUserLoginName\" />\r\n");
      out.write("                <table border=\"0\" width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                    <col span=\"1\" width=\"50px\" align=\"left\">\r\n");
      out.write("                    <col span=\"1\" width=\"10px\">\r\n");
      out.write("                    <col span=\"1\" width=\"*\" align=\"left\">\r\n");
      out.write("\r\n");
      out.write("                    <tr height=\"30\" >\r\n");
      out.write("                        <td bgcolor=\"f4f4f4\">&nbsp;<font size=\"-2\">");
      out.print(GlobalContext.getMessageForWeb("Status", loggedUserLocale) );
      out.write("</font></td>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td><select name=\"status\" size=\"1\" class=\"black\" >\r\n");
      out.write("                                <option value=\"All\">");
      out.print(GlobalContext.getMessageForWeb("All", loggedUserLocale) );
      out.write("</option>\r\n");
      out.write("                                <option value=\"Running\">");
      out.print(GlobalContext.getMessageForWeb("Running", loggedUserLocale) );
      out.write("</option>\r\n");
      out.write("                                <option value=\"Ready\">");
      out.print(GlobalContext.getMessageForWeb("Ready", loggedUserLocale) );
      out.write("</option>\r\n");
      out.write("                                <option value=\"Completed\">");
      out.print(GlobalContext.getMessageForWeb("Completed", loggedUserLocale) );
      out.write("</option>\r\n");
      out.write("                                <option value=\"Stopped\">");
      out.print(GlobalContext.getMessageForWeb("Stopped", loggedUserLocale) );
      out.write("</option>\r\n");
      out.write("                                <option value=\"Skipped\">");
      out.print(GlobalContext.getMessageForWeb("Skipped", loggedUserLocale) );
      out.write("</option>\r\n");
      out.write("                                <option value=\"Suspended\">");
      out.print(GlobalContext.getMessageForWeb("Suspended", loggedUserLocale) );
      out.write("</option>\r\n");
      out.write("                                <option value=\"Failed\">");
      out.print(GlobalContext.getMessageForWeb("Failed", loggedUserLocale) );
      out.write("</option>\r\n");
      out.write("                            </select></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"dotline\" colspan=\"3\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <!-- def id start-->\r\n");
      out.write("                    <tr height=\"30\">\r\n");
      out.write("                        <td bgcolor=\"f4f4f4\">&nbsp;<font size=\"-2\">");
      out.print(GlobalContext.getMessageForWeb("instance_id", loggedUserLocale) );
      out.write("</font></td>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td><input name=\"Instance\" type=\"text\"  class=\"gray\" size=\"20\" maxlength=\"20\" value=\"\" onBlur=\"validate_Number(this);\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"dotline\" colspan=\"3\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <!-- def id 2009-08-04 -->\r\n");
      out.write("                    <tr height=\"30\">\r\n");
      out.write("                        <td bgcolor=\"f4f4f4\">&nbsp;<font size=\"-2\">");
      out.print(GlobalContext.getMessageForWeb("Name", loggedUserLocale) );
      out.write("</font></td>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td><input name=\"docTitle\" type=\"text\"  class=\"gray\" size=\"20\" maxlength=\"20\" value=\"\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"dotline\" colspan=\"3\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <!-- starter start -->\r\n");
      out.write("                    <tr height=\"30\">\r\n");
      out.write("                        <td bgcolor=\"f4f4f4\">&nbsp;<font size=\"-2\">");
      out.print(GlobalContext.getMessageForWeb("Initiator", loggedUserLocale) );
      out.write("</font></td>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type='hidden' name='Initiator__which_is_xml_value' id=\"Initiator__which_is_xml_value\" value=\"\" size='1' >\r\n");
      out.write("                            <input type=\"hidden\" name=\"Initiator\" id=\"Initiator\" size='20' value=\"\"/>\r\n");
      out.write("                            <input type=\"text\" name=\"Initiator_display\" id=\"Initiator_display\" size='20' value=\"\" readonly=\"readonly\"/>\r\n");
      out.write("                            <img name=\"Initiator\" align=\"middle\" onclick='searchPeopleObj(this,true)' src='");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/processmanager/images/Toolbar-toblock.gif' style=\"cursor:pointer;\" alt=\"Initiator Search\" title=\"Initiator search\" />\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"dotline\" colspan=\"3\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <!-- starter 2009-08-04 -->\r\n");
      out.write("                    <!-- getter start -->\r\n");
      out.write("                    <tr height=\"30\">\r\n");
      out.write("                        <td bgcolor=\"f4f4f4\">&nbsp;<font size=\"-2\">");
      out.print(GlobalContext.getMessageForWeb("current_participant", loggedUserLocale) );
      out.write("</font></td>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td><input type='hidden' name='Nowperson__which_is_xml_value' id=\"Nowperson__which_is_xml_value\" value=\"\" size='1' >\r\n");
      out.write("                            <input type=\"hidden\" name=\"Nowperson\" id=\"Nowperson\" size='20' value=\"\"/>\r\n");
      out.write("                            <input type=\"text\" name=\"Nowperson_display\" id=\"Nowperson_display\" size='20' value=\"\" readonly=\"readonly\"/>\r\n");
      out.write("                            <img name=\"Nowperson\" align=\"middle\" onclick='searchPeopleObj(this,true)'   src='");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/processmanager/images/Toolbar-toblock.gif' style=\"cursor:pointer;\" alt=\"now person Search\" title=\"Now person search\" /></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"dotline\" colspan=\"3\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <!-- getter 2009-08-04 -->\r\n");
      out.write("                    <tr height=\"30\" >\r\n");
      out.write("                        <td bgcolor=\"f4f4f4\">&nbsp;<font size=\"-2\">");
      out.print(GlobalContext.getMessageForWeb("start_date", loggedUserLocale) );
      out.write("</font></td>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td><table>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td align=\"right\" width=\"38\" style=\"font-size:11px;\">");
      out.print(GlobalContext.getMessageForWeb("From", loggedUserLocale) );
      out.write(":</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <input type=\"text\" name=\"init_start_date\" id=\"init_start_date\" size=\"12\" value=\"\" class=\"j_calendar\"/>\r\n");
      out.write("                                        <!-- <img src=\"../images/icon_dayselect.gif\" style=\"cursor:hand\" name=\"init_start_date\" onClick=\"showFullcalendar('month', this.name);\" />-->\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td align=\"right\"  style=\"font-size:11px;\">");
      out.print(GlobalContext.getMessageForWeb("To", loggedUserLocale) );
      out.write(":</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <input type=\"text\" name=\"init_end_date\" id=\"init_end_date\" size=\"12\" value=\"\" class=\"j_calendar\" />\r\n");
      out.write("                                        <!--<img src=\"../images/icon_dayselect.gif\" style=\"cursor:hand\" name=\"init_end_date\" onClick=\"showFullcalendar('month', this.name);\" />-->\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </table></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"dotline\" colspan=\"3\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr height=\"30\">\r\n");
      out.write("                        <td bgcolor=\"f4f4f4\">&nbsp;<font size=\"-2\">");
      out.print(GlobalContext.getMessageForWeb("end_date", loggedUserLocale) );
      out.write("</font></td>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td><table>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td align=\"right\"  width=\"38\"  style=\"font-size:11px;\">");
      out.print(GlobalContext.getMessageForWeb("From", loggedUserLocale) );
      out.write(":</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <input type=\"text\" name=\"complete_start_date\" id=\"complete_start_date\" size=\"12\" value=\"\" class=\"j_calendar\" />\r\n");
      out.write("                                        <!--<img src=\"../images/icon_dayselect.gif\" style=\"cursor:hand\" name=\"complete_start_date\" onClick=\"showFullcalendar('month', this.name);\" /> -->\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td align=\"right\"  style=\"font-size:11px;\">");
      out.print(GlobalContext.getMessageForWeb("To", loggedUserLocale) );
      out.write(":</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <input type=\"text\" name=\"complete_end_date\" id=\"complete_end_date\" size=\"12\" value=\"\" class=\"j_calendar\" />\r\n");
      out.write("                                        <!--<img src=\"../images/icon_dayselect.gif\" style=\"cursor:hand\" name=\"complete_end_date\" onClick=\"showFullcalendar('month', this.name);\" /> -->\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </table></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"dotline\" colspan=\"3\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"3\"  height=\"10\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"3\" align=\"right\" ><img src=\"../images/Common/b_bigsearch.gif\" onClick=\"search()\" style=\"cursor: pointer;\" alt=\"search\"> <img src=\"../images/Common/b_refresh.gif\" onClick=\"searchForm.reset()\" style=\"cursor: pointer;\" alt=\"reset\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div dojoType=\"dijit.layout.AccordionPane\" title=\"");
      out.print(GlobalContext.getMessageForWeb("Search Definition", loggedUserLocale) );
      out.write("\">\r\n");
      out.write("            <form name=\"formSearchDefinition\" action=\"searchDefinition.jsp\" target=\"innerworkarea\" method=\"post\">\r\n");
      out.write("                <table border=\"0\" width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                    <tr height=\"30\">\r\n");
      out.write("                        <td width=\"50\" align=\"left\" bgcolor=\"f4f4f4\">&nbsp;<font size=\"-2\">");
      out.print(GlobalContext.getMessageForWeb("TYPE", loggedUserLocale) );
      out.write("</font></td>\r\n");
      out.write("                        <td width=\"10\"></td>\r\n");
      out.write("                        <td width=\"*\" align=\"left\">\r\n");
      out.write("                            <select name=\"inputObjType\" id=\"inputObjType\" style=\"width:100%;\" >\r\n");
      out.write("                                <option value=\"all\">");
      out.print(GlobalContext.getMessageForWeb("ALL", loggedUserLocale) );
      out.write("</option>\r\n");
      out.write("                                <option value=\"process\">");
      out.print(GlobalContext.getMessageForWeb("PROCESS", loggedUserLocale) );
      out.write("</option>\r\n");
      out.write("                                <option value=\"form\">");
      out.print(GlobalContext.getMessageForWeb("FORM", loggedUserLocale) );
      out.write("</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"dotline\" colspan=\"3\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr height=\"30\">\r\n");
      out.write("                        <td width=\"50\" align=\"left\" bgcolor=\"f4f4f4\">&nbsp;<font size=\"-2\">");
      out.print(GlobalContext.getMessageForWeb("NAME", loggedUserLocale) );
      out.write("</font></td>\r\n");
      out.write("                        <td width=\"10\"></td>\r\n");
      out.write("                        <td width=\"*\" align=\"left\"><input name=\"inputSearchWord\" type=\"text\" style=\"width:100%;\" /></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"dotline\" colspan=\"3\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr height=\"30\">\r\n");
      out.write("                        <td width=\"50\" align=\"left\" bgcolor=\"f4f4f4\">&nbsp;<font size=\"-2\">");
      out.print(GlobalContext.getMessageForWeb("ALIAS", loggedUserLocale) );
      out.write("</font></td>\r\n");
      out.write("                        <td width=\"10\"></td>\r\n");
      out.write("                        <td width=\"*\" align=\"left\"><input name=\"inputSearchAlias\" type=\"text\" style=\"width:100%;\" /></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"dotline\" colspan=\"3\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"3\"  height=\"10\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td align=\"right\"><img src=\"../images/Common/b_bigsearch.gif\" onClick=\"document.formSearchDefinition.submit()\" style=\"cursor: pointer;\" alt=\"search\" /> \r\n");
      out.write("                        <img src=\"../images/Common/b_refresh.gif\" onClick=\"document.formSearchDefinition.reset()\" style=\"cursor: pointer;\" alt=\"reset\" /></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<form name=\"newRuleDefinition\" action=\"newRuleDefinition.jsp\" method=\"get\" target=\"innerworkarea\">\r\n");
      out.write("    <input type=\"hidden\" name=\"folderId\">\r\n");
      out.write("</form>\r\n");
      out.write("<form name=\"newClassDefinition\" action=\"newClassDefinition.jsp\" method=\"get\" target=\"innerworkarea\">\r\n");
      out.write("    <input type=\"hidden\" name=\"folderId\">\r\n");
      out.write("</form>\r\n");
      out.write("<form name=\"newFormDefinition\" action=\"newFormDefinition.jsp\" method=\"get\" target=\"innerworkarea\">\r\n");
      out.write("    <input type=\"hidden\" name=\"folderId\">\r\n");
      out.write("</form>\r\n");
      out.write("<form name=\"newFormDefinitionUSFeditor\" action=\"newFormDefinitionUSFeditor.jsp\" method=\"get\" target=\"innerworkarea\">\r\n");
      out.write("    <input type=\"hidden\" name=\"folderId\">\r\n");
      out.write("</form>\r\n");
      out.write("<form name=\"newDatabaseSet\" action=\"../crud/CRUDSetIndex.jsp\" method=\"get\" target=\"innerworkarea\">\r\n");
      out.write("    <input type=\"hidden\" name=\"folderId\">\r\n");
      out.write("</form>\r\n");
      out.write("<form name=\"viewProcessDefinition\" action=\"viewProcessFlowChart.jsp\" method=\"get\" target=\"innerworkarea\">\r\n");
      out.write("    <input type=\"hidden\" name=\"processDefinition\">\r\n");
      out.write("    <input type=\"hidden\" name=\"folder\">\r\n");
      out.write("</form>\r\n");
      out.write("<form name=\"viewRuleDefinition\" action=\"viewRuleDefinition.jsp\" method=\"get\" target=\"innerworkarea\">\r\n");
      out.write("    <input type=\"hidden\" name=\"objectDefinitionId\">\r\n");
      out.write("    <input type=\"hidden\" name=\"folder\">\r\n");
      out.write("</form>\r\n");
      out.write("<form name=\"viewClassDefinition\" action=\"viewClassDefinition.jsp\" method=\"get\" target=\"innerworkarea\">\r\n");
      out.write("    <input type=\"hidden\" name=\"objectDefinitionId\">\r\n");
      out.write("    <input type=\"hidden\" name=\"folder\">\r\n");
      out.write("</form>\r\n");
      out.write("<form name=\"viewCalcDefinition\" action=\"viewCalcDefinition.jsp\" method=\"get\" target=\"innerworkarea\">\r\n");
      out.write("    <input type=\"hidden\" name=\"objectDefinitionId\">\r\n");
      out.write("    <input type=\"hidden\" name=\"folder\">\r\n");
      out.write("</form>\r\n");
      out.write("<form name=\"viewFormDefinition\" action=\"viewFormDefinition.jsp\" method=\"get\" target=\"innerworkarea\">\r\n");
      out.write("    <input type=\"hidden\" name=\"objectDefinitionId\">\r\n");
      out.write("    <input type=\"hidden\" name=\"folder\">\r\n");
      out.write("</form>\r\n");
      out.write("<form name=\"viewFormDefinitionUSFeditor\" action=\"viewFormDefinitionUSFeditor.jsp\" method=\"get\" target=\"innerworkarea\">\r\n");
      out.write("    <input type=\"hidden\" name=\"objectDefinitionId\">\r\n");
      out.write("    <input type=\"hidden\" name=\"folder\">\r\n");
      out.write("</form>\r\n");
      out.write("<form name=\"viewDatabaseSet\" action=\"../crud/CRUDSetIndex.jsp\" method=\"get\" target=\"innerworkarea\">\r\n");
      out.write("    <input type=\"hidden\" name=\"objectDefinitionId\">\r\n");
      out.write("    <input type=\"hidden\" name=\"folder\">\r\n");
      out.write("</form>\r\n");
      out.write("<form name=\"addFolderForm\" action=\"addFolder.jsp\" method=\"POST\" >\r\n");
      out.write("    <input type=\"hidden\" name=\"folderName\">\r\n");
      out.write("    <input type=\"hidden\" name=\"parentFolder\">\r\n");
      out.write("</form>\r\n");
      out.write("<form name=\"toggleVisibleForm\" action=\"toggleVisible.jsp\" method=\"get\" >\r\n");
      out.write("    <input type=\"hidden\" name=\"definitionId\">\r\n");
      out.write("    <input type=\"hidden\" name=\"visible\">\r\n");
      out.write("</form>\r\n");
      out.write("<form name=\"actionForm\" action=\"renameProcessDefinition.jsp\" method=\"POST\">\r\n");
      out.write("    <input type=\"hidden\" name=\"processDefinition\">\r\n");
      out.write("    <input type=\"hidden\" name=\"newName\">\r\n");
      out.write("</form>\r\n");
      out.write("<form name=\"removeForm\" action=\"removeFolder.jsp\" method=\"POST\">\r\n");
      out.write("    <input type=\"hidden\" name=\"folder\">\r\n");
      out.write("</form>\r\n");
      out.write("<form name=\"exportDef\" action=\"exportDefinition.jsp\" method=\"POST\">\r\n");
      out.write("    <input type=\"hidden\" name=\"processDefinition\">\r\n");
      out.write("    <input type=\"hidden\" name=\"filePath\">\r\n");
      out.write("</form>\r\n");
      out.write("<form name=\"accessibility\" action=\"../authority/authority.jsp\" method=\"POST\" target=\"innerworkarea\">\r\n");
      out.write("    <input type=\"hidden\" name=\"defId\">\r\n");
      out.write("    <input type=\"hidden\" name=\"defName\">\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div dojoType=\"dijit.layout.ContentPane\" region=\"center\" id=\"centerPane\" style=\"overflow: hidden;\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction changeTitle(iframe)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById(\"divPageTitle\").innerHTML = iframe.contentWindow.document.title;\r\n");
      out.write("\t\tvar navi = iframe.contentWindow.document.navigation;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(navi)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar navis = navi.split(\";\");\r\n");
      out.write("\t\t\tvar sNavi = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\tfor(var i = 0; i < navis.length; i++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tsNavi += \" <img src=\\\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/Common/i_blue03.gif\\\"> \" + navis[i];\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.getElementById(\"divPageNavi\").innerHTML = sNavi;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tresizeFrame(iframe);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"pagrtitlebg\" id=\"divPageTitleBar\">\r\n");
      out.write("\t<div class=\"pagetitleicon\"><img src=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/Common/lc05711.gif\"></div>\r\n");
      out.write("\t<div class=\"pagetitletitle\" id=\"divPageTitle\"></div>\r\n");
      out.write("\t<div class=\"pagrtitlenavi\" id=\"divPageNavi\"></div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t     <iframe onresize=\"resizeFrame(this);\" onload=\"changeTitle(this);\" style=\"width: 100%; height: 100%; padding-bottom: 30px;\" src=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT );
      out.write("/processmanager/processInstanceList.jsp\" \r\n");
      out.write("\t     name=\"innerworkarea\" frameborder=\"0\"></iframe>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"footer\" style=\"border:solid 0px white; background-color: #F0F0F0;\" dojotype=\"dijit.layout.ContentPane\" region=\"bottom\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<div style=\"margin-top: -5px; margin-right:30; text-align: right;\"><!-- position:absolute; bottom:-2px; right:30px; border:solid 0px white; -->\r\n");
      out.write("<img src=\"");
      out.print(GlobalContext.WEB_CONTEXT_ROOT);
      out.write("/images/Common/tailbtn.gif\" width=\"398\" height=\"30\" usemap=\"#Map\" />\r\n");
      out.write("<map name=\"Map\" id=\"Map\"><area shape=\"rect\" coords=\"295,7,388,24\" href=\"http://uengine.org/web/guest/home\" target=\"_blank\" /></map>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
